spring:
  rabbitmq:
    host: products-rabbit
    port: 5673
    username: guest
    password: guest
    queue:
      name: list_products_queue
      key: list_products

#spring.rabbitmq.host=products-rabbit
#spring.rabbitmq.port=5673
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest