spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:33061/products_task?autoReconnect=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  flyway:
    baselineOnMigrate: true